# HTML_WORKBENCH_MANAGED_HOST_V1
server {
    listen 80;
    server_name ho.wekki.fun;
    include /etc/nginx/snippets/html-workbench-admin-routes.conf;
}

server {
    listen 80;
    server_name page.wekki.fun;
    include /etc/nginx/snippets/html-workbench-content-routes.conf;
}
